//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InoSoft.TeamStudio.Core.Entities
{
    public partial class aspnet_PersonalizationAllUsers
    {
        #region Primitive Properties
    
        public virtual System.Guid PathId
        {
            get { return _pathId; }
            set
            {
                if (_pathId != value)
                {
                    if (aspnet_Paths != null && aspnet_Paths.PathId != value)
                    {
                        aspnet_Paths = null;
                    }
                    _pathId = value;
                }
            }
        }
        private System.Guid _pathId;
    
        public virtual byte[] PageSettings
        {
            get;
            set;
        }
    
        public virtual System.DateTime LastUpdatedDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual aspnet_Paths aspnet_Paths
        {
            get { return _aspnet_Paths; }
            set
            {
                if (!ReferenceEquals(_aspnet_Paths, value))
                {
                    var previousValue = _aspnet_Paths;
                    _aspnet_Paths = value;
                    Fixupaspnet_Paths(previousValue);
                }
            }
        }
        private aspnet_Paths _aspnet_Paths;

        #endregion
        #region Association Fixup
    
        private void Fixupaspnet_Paths(aspnet_Paths previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.aspnet_PersonalizationAllUsers, this))
            {
                previousValue.aspnet_PersonalizationAllUsers = null;
            }
    
            if (aspnet_Paths != null)
            {
                aspnet_Paths.aspnet_PersonalizationAllUsers = this;
                if (PathId != aspnet_Paths.PathId)
                {
                    PathId = aspnet_Paths.PathId;
                }
            }
        }

        #endregion
    }
}
