//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InoSoft.TeamStudio.Core.Entities
{
    public partial class aspnet_Roles
    {
        #region Primitive Properties
    
        public virtual System.Guid ApplicationId
        {
            get { return _applicationId; }
            set
            {
                if (_applicationId != value)
                {
                    if (aspnet_Applications != null && aspnet_Applications.ApplicationId != value)
                    {
                        aspnet_Applications = null;
                    }
                    _applicationId = value;
                }
            }
        }
        private System.Guid _applicationId;
    
        public virtual System.Guid RoleId
        {
            get;
            set;
        }
    
        public virtual string RoleName
        {
            get;
            set;
        }
    
        public virtual string LoweredRoleName
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual aspnet_Applications aspnet_Applications
        {
            get { return _aspnet_Applications; }
            set
            {
                if (!ReferenceEquals(_aspnet_Applications, value))
                {
                    var previousValue = _aspnet_Applications;
                    _aspnet_Applications = value;
                    Fixupaspnet_Applications(previousValue);
                }
            }
        }
        private aspnet_Applications _aspnet_Applications;
    
        public virtual ICollection<aspnet_Users> aspnet_Users
        {
            get
            {
                if (_aspnet_Users == null)
                {
                    var newCollection = new FixupCollection<aspnet_Users>();
                    newCollection.CollectionChanged += Fixupaspnet_Users;
                    _aspnet_Users = newCollection;
                }
                return _aspnet_Users;
            }
            set
            {
                if (!ReferenceEquals(_aspnet_Users, value))
                {
                    var previousValue = _aspnet_Users as FixupCollection<aspnet_Users>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupaspnet_Users;
                    }
                    _aspnet_Users = value;
                    var newValue = value as FixupCollection<aspnet_Users>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupaspnet_Users;
                    }
                }
            }
        }
        private ICollection<aspnet_Users> _aspnet_Users;

        #endregion
        #region Association Fixup
    
        private void Fixupaspnet_Applications(aspnet_Applications previousValue)
        {
            if (previousValue != null && previousValue.aspnet_Roles.Contains(this))
            {
                previousValue.aspnet_Roles.Remove(this);
            }
    
            if (aspnet_Applications != null)
            {
                if (!aspnet_Applications.aspnet_Roles.Contains(this))
                {
                    aspnet_Applications.aspnet_Roles.Add(this);
                }
                if (ApplicationId != aspnet_Applications.ApplicationId)
                {
                    ApplicationId = aspnet_Applications.ApplicationId;
                }
            }
        }
    
        private void Fixupaspnet_Users(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (aspnet_Users item in e.NewItems)
                {
                    if (!item.aspnet_Roles.Contains(this))
                    {
                        item.aspnet_Roles.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (aspnet_Users item in e.OldItems)
                {
                    if (item.aspnet_Roles.Contains(this))
                    {
                        item.aspnet_Roles.Remove(this);
                    }
                }
            }
        }

        #endregion
    }
}
