//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InoSoft.TeamStudio.Core.Entities
{
    public partial class LanguageLetter
    {
        #region Primitive Properties
    
        public virtual int LanguageLetterId
        {
            get;
            set;
        }
    
        public virtual int LetterId
        {
            get { return _letterId; }
            set
            {
                if (_letterId != value)
                {
                    if (Letter != null && Letter.LetterId != value)
                    {
                        Letter = null;
                    }
                    _letterId = value;
                }
            }
        }
        private int _letterId;
    
        public virtual Nullable<int> LanguageId
        {
            get;
            set;
        }
    
        public virtual string Template
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Letter Letter
        {
            get { return _letter; }
            set
            {
                if (!ReferenceEquals(_letter, value))
                {
                    var previousValue = _letter;
                    _letter = value;
                    FixupLetter(previousValue);
                }
            }
        }
        private Letter _letter;

        #endregion
        #region Association Fixup
    
        private void FixupLetter(Letter previousValue)
        {
            if (previousValue != null && previousValue.LanguageLetters.Contains(this))
            {
                previousValue.LanguageLetters.Remove(this);
            }
    
            if (Letter != null)
            {
                if (!Letter.LanguageLetters.Contains(this))
                {
                    Letter.LanguageLetters.Add(this);
                }
                if (LetterId != Letter.LetterId)
                {
                    LetterId = Letter.LetterId;
                }
            }
        }

        #endregion
    }
}
