//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace InoSoft.TeamStudio.Core.Entities
{
    public partial class Letter
    {
        #region Primitive Properties
    
        public virtual int LetterId
        {
            get;
            set;
        }
    
        public virtual string LetterName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<LanguageLetter> LanguageLetters
        {
            get
            {
                if (_languageLetters == null)
                {
                    var newCollection = new FixupCollection<LanguageLetter>();
                    newCollection.CollectionChanged += FixupLanguageLetters;
                    _languageLetters = newCollection;
                }
                return _languageLetters;
            }
            set
            {
                if (!ReferenceEquals(_languageLetters, value))
                {
                    var previousValue = _languageLetters as FixupCollection<LanguageLetter>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLanguageLetters;
                    }
                    _languageLetters = value;
                    var newValue = value as FixupCollection<LanguageLetter>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLanguageLetters;
                    }
                }
            }
        }
        private ICollection<LanguageLetter> _languageLetters;

        #endregion
        #region Association Fixup
    
        private void FixupLanguageLetters(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (LanguageLetter item in e.NewItems)
                {
                    item.Letter = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (LanguageLetter item in e.OldItems)
                {
                    if (ReferenceEquals(item.Letter, this))
                    {
                        item.Letter = null;
                    }
                }
            }
        }

        #endregion
    }
}
