//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace InoSoft.TeamStudio.Core.Entities
{
    public partial class TeamStudioEntities : ObjectContext
    {
        public const string ConnectionString = "name=TeamStudioEntities";
        public const string ContainerName = "TeamStudioEntities";
    
        #region Constructors
    
        public TeamStudioEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public TeamStudioEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public TeamStudioEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<aspnet_Users> aspnet_Users
        {
            get { return _aspnet_Users  ?? (_aspnet_Users = CreateObjectSet<aspnet_Users>("aspnet_Users")); }
        }
        private ObjectSet<aspnet_Users> _aspnet_Users;
    
        public ObjectSet<Project> Projects
        {
            get { return _projects  ?? (_projects = CreateObjectSet<Project>("Projects")); }
        }
        private ObjectSet<Project> _projects;
    
        public ObjectSet<Task> Tasks
        {
            get { return _tasks  ?? (_tasks = CreateObjectSet<Task>("Tasks")); }
        }
        private ObjectSet<Task> _tasks;
    
        public ObjectSet<Team> Teams
        {
            get { return _teams  ?? (_teams = CreateObjectSet<Team>("Teams")); }
        }
        private ObjectSet<Team> _teams;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<Version> Versions
        {
            get { return _versions  ?? (_versions = CreateObjectSet<Version>("Versions")); }
        }
        private ObjectSet<Version> _versions;
    
        public ObjectSet<LanguageLetter> LanguageLetters
        {
            get { return _languageLetters  ?? (_languageLetters = CreateObjectSet<LanguageLetter>("LanguageLetters")); }
        }
        private ObjectSet<LanguageLetter> _languageLetters;
    
        public ObjectSet<Letter> Letters
        {
            get { return _letters  ?? (_letters = CreateObjectSet<Letter>("Letters")); }
        }
        private ObjectSet<Letter> _letters;

        #endregion
    }
}
